/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColoredPetriNet: typeof import('./src/components/cpn/ColoredPetriNet.vue')['default']
    CPNAnalysis: typeof import('./src/components/cpn/CPNAnalysis.vue')['default']
    CPNArcEdge: typeof import('./src/components/cpn/CPNArcEdge.vue')['default']
    CPNArcEditDialog: typeof import('./src/components/cpn/CPNArcEditDialog.vue')['default']
    CPNColorSetBuilder: typeof import('./src/components/cpn/CPNColorSetBuilder.vue')['default']
    CPNNodeEditDialog: typeof import('./src/components/cpn/CPNNodeEditDialog.vue')['default']
    CPNPlaceNode: typeof import('./src/components/cpn/CPNPlaceNode.vue')['default']
    CPNpyAnalysisPanel: typeof import('./src/components/cpn/CPNpyAnalysisPanel.vue')['default']
    CPNSidebar: typeof import('./src/components/cpn/CPNSidebar.vue')['default']
    CPNTransitionNode: typeof import('./src/components/cpn/CPNTransitionNode.vue')['default']
    CPNVariableEditor: typeof import('./src/components/cpn/CPNVariableEditor.vue')['default']
    DeadlockDetailsModal: typeof import('./src/components/behavior/DeadlockDetailsModal.vue')['default']
    EFSMVariablesPanel: typeof import('./src/components/behavior/EFSMVariablesPanel.vue')['default']
    EncapsulationMultipleSelectModal: typeof import('./src/components/modals/EncapsulationMultipleSelectModal.vue')['default']
    EncapsulationVisualization: typeof import('./src/components/breadcrumbs/EncapsulationVisualization.vue')['default']
    ExportDropdownButton: typeof import('./src/components/common/ExportDropdownButton.vue')['default']
    ExportModal: typeof import('./src/components/modals/ExportModal.vue')['default']
    FieldDeleteModal: typeof import('./src/components/modals/FieldDeleteModal.vue')['default']
    FieldEditModal: typeof import('./src/components/modals/FieldEditModal.vue')['default']
    FieldEncapsulateModal: typeof import('./src/components/modals/FieldEncapsulateModal.vue')['default']
    FieldListManager: typeof import('./src/components/FieldListManager.vue')['default']
    FieldTab: typeof import('./src/components/modals/fieldedittabs/FieldTab.vue')['default']
    FiniteStateMachine: typeof import('./src/components/behavior/FiniteStateMachine.vue')['default']
    FSMAnalysis: typeof import('./src/components/behavior/FSMAnalysis.vue')['default']
    FSMEventsPanel: typeof import('./src/components/behavior/FSMEventsPanel.vue')['default']
    FSMSidebar: typeof import('./src/components/behavior/FSMSidebar.vue')['default']
    FSMStateEditDialog: typeof import('./src/components/behavior/FSMStateEditDialog.vue')['default']
    FSMStateNode: typeof import('./src/components/behavior/FSMStateNode.vue')['default']
    FSMTransitionEdge: typeof import('./src/components/behavior/FSMTransitionEdge.vue')['default']
    FSMTransitionEditDialog: typeof import('./src/components/behavior/FSMTransitionEditDialog.vue')['default']
    GenericTab: typeof import('./src/components/modals/settingstabs/GenericTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftDrawer: typeof import('./src/components/navs/LeftDrawer.vue')['default']
    LibraryModal: typeof import('./src/components/modals/LibraryModal.vue')['default']
    OptionTab: typeof import('./src/components/modals/fieldedittabs/OptionTab.vue')['default']
    ProfileAvatar: typeof import('./src/components/ProfileAvatar.vue')['default']
    ProtocolBreadcrumbs: typeof import('./src/components/breadcrumbs/ProtocolBreadcrumbs.vue')['default']
    ProtocolEncapsulation: typeof import('./src/components/ProtocolEncapsulation.vue')['default']
    ProtocolLibrary: typeof import('./src/components/ProtocolLibrary.vue')['default']
    ProtocolProperties: typeof import('./src/components/ProtocolProperties.vue')['default']
    ProtocolUpload: typeof import('./src/components/ProtocolUpload.vue')['default']
    ProtocolViewer: typeof import('./src/components/ProtocolViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/modals/SettingsModal.vue')['default']
  }
}
