/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EncapsulationMultipleSelectModal: typeof import('./src/components/modals/EncapsulationMultipleSelectModal.vue')['default']
    EncapsulationVisualization: typeof import('./src/components/breadcrumbs/EncapsulationVisualization.vue')['default']
    ExportModal: typeof import('./src/components/modals/ExportModal.vue')['default']
    FieldDeleteModal: typeof import('./src/components/modals/FieldDeleteModal.vue')['default']
    FieldEditModal: typeof import('./src/components/modals/FieldEditModal.vue')['default']
    FieldEncapsulateModal: typeof import('./src/components/modals/FieldEncapsulateModal.vue')['default']
    FieldListManager: typeof import('./src/components/FieldListManager.vue')['default']
    FieldTab: typeof import('./src/components/modals/fieldedittabs/FieldTab.vue')['default']
    GenericTab: typeof import('./src/components/modals/settingstabs/GenericTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftDrawer: typeof import('./src/components/navs/LeftDrawer.vue')['default']
    LibraryModal: typeof import('./src/components/modals/LibraryModal.vue')['default']
    OptionTab: typeof import('./src/components/modals/fieldedittabs/OptionTab.vue')['default']
    ProfileAvatar: typeof import('./src/components/ProfileAvatar.vue')['default']
    ProtocolBreadcrumbs: typeof import('./src/components/breadcrumbs/ProtocolBreadcrumbs.vue')['default']
    ProtocolEncapsulation: typeof import('./src/components/ProtocolEncapsulation.vue')['default']
    ProtocolLibrary: typeof import('./src/components/ProtocolLibrary.vue')['default']
    ProtocolProperties: typeof import('./src/components/ProtocolProperties.vue')['default']
    ProtocolUpload: typeof import('./src/components/ProtocolUpload.vue')['default']
    ProtocolViewer: typeof import('./src/components/ProtocolViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/modals/SettingsModal.vue')['default']
  }
}
