/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFieldModal: typeof import('./src/components/modals/AddFieldModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProtocolEditModal: typeof import('./src/components/modals/ProtocolEditModal.vue')['default']
    ProtocolInfoModal: typeof import('./src/components/modals/ProtocolInfoModal.vue')['default']
    ProtocolUpload: typeof import('./src/components/ProtocolUpload.vue')['default']
    ProtocolViewer: typeof import('./src/components/ProtocolViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
