"""
CPNpy Analysis Endpoint - Tier-3 state-space verification via cpnpy

Receives a CPN Tools 4.x XML string (generated by the frontend's
exportToCPNTools()), runs cpnpy's StateSpaceAnalyzer (with an
empty-multiset bug workaround), and returns:
  - Reachability graph node / arc counts
  - Dead markings (terminal states) with human-readable token strings
  - Dead / live / impartial transitions
  - Per-place token bounds
  - SCC graph stats and home markings
  - Computation time
"""
import os
import re
import tempfile
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from src.auth.jwthandler import get_current_user

router = APIRouter()

try:
    from cpnpy.util.conversion.cpn_xml_to_json import cpn_xml_to_json as _cpn_xml_to_json
    from cpnpy.cpn import importer as _cpn_importer
    from cpnpy.cpn.cpn_imp import Marking as _CPNMarking
    from cpnpy.analysis.reachability import (
        build_reachability_graph as _build_rg,
        make_hashable as _make_hashable,
    )
    from cpnpy.analysis.scc import build_scc_graph as _build_scc
    from cpnpy.analysis.analyzer import StateSpaceAnalyzer as _StateSpaceAnalyzer
    CPNPY_AVAILABLE = True
except ImportError:
    CPNPY_AVAILABLE = False


# -----------------------------------------------------------------------------
#  Target-marking reachability helpers
# -----------------------------------------------------------------------------

def _node_token_counts(node_key: Tuple) -> Dict[str, int]:
    """Extract {place_name: token_count} from a normalised RG node key."""
    _ts, places = node_key
    return {name: len(toks) for name, toks in places}


def _check_target_reachability(
    analyzer: Any,
    initial_key: Tuple,
    conditions: List[Dict],
) -> Dict[str, Any]:
    """
    Given a fully-built StateSpaceAnalyzer, find all nodes that satisfy
    every condition and check whether any of them is reachable from the
    initial marking.

    conditions: list of {"placeName": str, "minTokens": int}
    """
    if not conditions:
        return {"queried": False, "reachable": False, "matchingMarkings": 0, "description": ""}

    description = " \u2227 ".join(
        f'{c["placeName"]} \u2265 {c["minTokens"]}' for c in conditions
    )

    # Collect nodes that satisfy all conditions.
    matching: List[Tuple] = [
        node for node in analyzer.RG.nodes()
        if all(
            _node_token_counts(node).get(c["placeName"], 0) >= c["minTokens"]
            for c in conditions
        )
    ]

    if not matching:
        return {
            "queried": True,
            "reachable": False,
            "matchingMarkings": 0,
            "description": description,
        }

    reachable_count = 0
    for target in matching:
        if target == initial_key:
            reachable_count += 1
            continue
        try:
            reached = analyzer.is_reachable(initial_key, target)
        except Exception:
            reached = False
        if reached:
            reachable_count += 1

    return {
        "queried": True,
        "reachable": reachable_count > 0,
        "matchingMarkings": reachable_count,
        "description": description,
    }


# -----------------------------------------------------------------------------
#  SML to Python translation helpers
# -----------------------------------------------------------------------------

def _sml_guard_to_python(raw: str) -> str:
    raw = raw.strip()
    raw = re.sub(r"\btrue\b",  "True",  raw)
    raw = re.sub(r"\bfalse\b", "False", raw)
    raw = re.sub(r"\bmod\b",   "%",     raw)
    raw = raw.replace("<>", "!=")
    raw = re.sub(r"(?<![=!<>])=(?!=)", "==", raw)
    return raw


def _sml_arc_to_python(expr: str) -> str:
    """
    Convert a CPN Tools SML arc inscription to a valid Python expression
    that cpnpy's EvaluationContext.evaluate_arc() can eval().

    Handles:
      - Simple variable:          b         → b
      - Simple literal:           b_in      → b_in
      - Single-count multiset:    1`0       → [0]*(1)
      - Variable-count multiset:  b`0       → [0]*(b)
      - Compound multiset (++):   b`0 ++ (1-b)`1  → [0]*(b) + [1]*((1-b))
    """
    expr = expr.strip()

    # If the expression contains backtick notation, convert to Python list expr
    if "`" in expr:
        python_parts: List[str] = []
        for part in expr.split("++"):
            part = part.strip()
            if not part or part in ("0", "empty"):
                continue
            # Strip @time suffix before processing
            time_val = ""
            at_match = re.search(r"@\+?([\d.]+)$", part)
            if at_match:
                time_val = at_match.group(0)
                part = part[: at_match.start()].strip()
            bt = part.find("`")
            if bt == -1:
                # No backtick in this sub-term — plain value
                token = re.sub(r"\btrue\b", "True", part)
                token = re.sub(r"\bfalse\b", "False", token)
                python_parts.append(f"[{token}]")
            else:
                count_str = part[:bt].strip() or "1"
                color_str = part[bt + 1:].strip()
                count_str = re.sub(r"\btrue\b", "True", count_str)
                count_str = re.sub(r"\bfalse\b", "False", count_str)
                color_str = re.sub(r"\btrue\b", "True", color_str)
                color_str = re.sub(r"\bfalse\b", "False", color_str)
                python_parts.append(f"[{color_str}]*({count_str})")
        if not python_parts:
            return "[]"
        return " + ".join(python_parts)

    # No backtick — simple expression (variable name or literal)
    expr = re.sub(r"\btrue\b",  "True",  expr)
    expr = re.sub(r"\bfalse\b", "False", expr)
    return expr


_NOT_VAR_NAMES = {"True", "False", "None", "and", "or", "not", "in", "is"}


def _arc_vars(expr: str) -> List[str]:
    result = []
    for name in re.findall(r"[a-zA-Z_]\w*", expr):
        if name not in _NOT_VAR_NAMES and name[0].islower() and name not in result:
            result.append(name)
    return result


def _fix_token(tok: Any) -> Any:
    if tok == "true":  return True
    if tok == "false": return False
    return tok


def _parse_token_value(raw: str) -> Any:
    """Parse a single token value string into a Python object."""
    raw = raw.strip()
    if raw in ("()", ""):
        return ()
    if raw == "true":  return True
    if raw == "false": return False
    try:
        return int(raw)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        pass
    return raw


def _expand_multiset_marking(raw: str) -> Tuple[List[Any], List[float]]:
    """
    Correctly parse a CPN multiset marking string, expanding multiplicities.

    Fixes cpnpy's parse_marking_expr which silently ignores the count before
    the backtick (e.g. '100`()' is treated as one token instead of 100).

    Returns (tokens, timestamps) — both parallel lists ready for the importer.
    """
    tokens: List[Any] = []
    timestamps: List[float] = []
    for part in raw.split("++"):
        part = part.strip()
        if not part or part in ("0", "empty"):
            continue
        # Strip @time suffix
        time_val = 0.0
        at_match = re.search(r"@([\d.]+)$", part)
        if at_match:
            try:
                time_val = float(at_match.group(1))
            except ValueError:
                pass
            part = part[: at_match.start()].strip()
        bt = part.find("`")
        if bt == -1:
            tokens.append(_parse_token_value(part))
            timestamps.append(time_val)
            continue
        count_str = part[:bt].strip()
        color_str = part[bt + 1:].strip()
        try:
            count = int(count_str) if count_str else 1
        except ValueError:
            count = 1
        tok = _parse_token_value(color_str)
        tokens.extend([tok] * count)
        timestamps.extend([time_val] * count)
    return tokens, timestamps


# -----------------------------------------------------------------------------
#  cpnpy empty-multiset bug workaround (this only happens in CPNpy. CPN Tools agrees with our implementation.)
#  remove_tokens() leaves empty Multiset entries in _marking, causing
#  semantically identical markings to hash differently depending on path.
# -----------------------------------------------------------------------------

def _normalized_equiv(m: Any) -> Tuple:
    entries = []
    for place_name, ms in sorted(m._marking.items()):
        if not ms.tokens:
            continue
        tok_list = tuple(
            sorted((_make_hashable(t.value), _make_hashable(t.timestamp))
                   for t in ms.tokens)
        )
        entries.append((place_name, tok_list))
    return (m.global_clock, tuple(entries))


# -----------------------------------------------------------------------------
#  Core analysis pipeline
# -----------------------------------------------------------------------------

def run_cpnpy_analysis(xml_str: str, target_conditions: Optional[List[Dict]] = None) -> Dict[str, Any]:
    """
    Write XML to a temp file, run the full cpnpy state-space pipeline,
    and return a plain dict of results.
    """
    with tempfile.NamedTemporaryFile(suffix=".cpn", mode="w", encoding="iso-8859-1", delete=False) as fh:
        fh.write(xml_str)
        tmp_path = fh.name

    try:
        # 1. XML to cpnpy JSON dict
        data = _cpn_xml_to_json(tmp_path)

        # strip range (no support in cpnpy)
        data["colorSets"] = [
            re.sub(r"\bint\s+with\s+-?\d+\.\.-?\d+\b", "int", cs)
            for cs in data.get("colorSets", [])
        ]

        # 2. adjust guards: cpn_xml_to_json reads <condition/annot/text> but CPN Tools 4 / our exporter stores guards in <cond><text>.
        tree = ET.parse(tmp_path)
        root = tree.getroot()
        trans_guard: Dict[str, str] = {}
        for t_elem in root.findall(".//trans"):
            tname_elt = t_elem.find("text")
            tname = tname_elt.text.strip() if (tname_elt is not None and tname_elt.text) else ""
            cond = t_elem.find("cond")
            if cond is not None:
                txt = cond.find("text")
                if txt is not None and txt.text and txt.text.strip():
                    trans_guard[tname] = _sml_guard_to_python(txt.text)
        for t in data["transitions"]:
            if t["name"] in trans_guard:
                t["guard"] = trans_guard[t["name"]]

        # 3. Fix arc expressions and derive missing variable lists
        for t in data["transitions"]:
            t["inArcs"]  = [{"place": a["place"],
                              "expression": _sml_arc_to_python(a["expression"])}
                             for a in t["inArcs"]]
            t["outArcs"] = [{"place": a["place"],
                              "expression": _sml_arc_to_python(a["expression"])}
                             for a in t["outArcs"]]
            if not t["variables"]:
                seen: List[str] = []
                for a in t["inArcs"]:
                    for v in _arc_vars(a["expression"]):
                        if v not in seen:
                            seen.append(v)
                t["variables"] = seen

        # 4. Fix initial markings: cpnpy's parser ignores the count multiplier
        #    (e.g. 100`() is parsed as 1 token, not 100). Re-parse from the XML
        #    ourselves using our own expander, and also fix boolean tokens.
        for place_elem in root.findall(".//place"):
            pname_elt = place_elem.find("text")
            if pname_elt is None or not pname_elt.text:
                continue
            pname = pname_elt.text.strip()
            initmark_elem = place_elem.find("initmark")
            if initmark_elem is None:
                continue
            txt_elt = initmark_elem.find("text")
            if txt_elt is None or not txt_elt.text:
                continue
            raw = txt_elt.text.strip()
            if raw in ("", "0", "empty"):
                data["initialMarking"].pop(pname, None)
                continue
            toks, stamps = _expand_multiset_marking(raw)
            if toks:
                data["initialMarking"][pname] = {"tokens": toks, "timestamps": stamps}
            else:
                data["initialMarking"].pop(pname, None)

        # 5. Build cpnpy model objects
        cpn_obj, marking, context = _cpn_importer.import_cpn_from_json(data)

        # 6. Build corrected reachability graph
        initial_node_key = _normalized_equiv(marking)
        analyzer = _StateSpaceAnalyzer(cpn_obj, marking, context)
        analyzer.RG = _build_rg(cpn_obj, marking, context,
                                 marking_equiv_func=_normalized_equiv)
        analyzer.SG = _build_scc(analyzer.RG)
        analyzer.marking_to_enabled_transitions = {}
        analyzer._precompute_enabled_transitions()

        report = analyzer.summarize()

        # 7. Decode dead markings into human-readable {place: token_string} dicts
        def _decode_dead(node_key: Tuple) -> Dict[str, str]:
            _ts, places = node_key
            out: Dict[str, str] = {}
            for name, toks in places:
                if toks:
                    strs = []
                    for val, _stamp in toks:
                        if val == ():
                            strs.append("1`()")
                        elif isinstance(val, bool):
                            strs.append(f"1`{'true' if val else 'false'}")
                        else:
                            strs.append(f"1`{val}")
                    out[name] = " ++ ".join(strs)
                else:
                    out[name] = "empty"
            return out

        stats = report.get("statistics", {})
        bounds = report.get("place_bounds", {})

        target_reach = _check_target_reachability(
            analyzer, initial_node_key, target_conditions or []
        )

        return {
            "available": True,
            "rgNodes": stats.get("RG_nodes", 0),
            "rgArcs": stats.get("RG_arcs", 0),
            "sccNodes": stats.get("SCC_nodes", 0),
            "sccArcs": stats.get("SCC_arcs", 0),
            "deadMarkings": [_decode_dead(n) for n in report.get("dead_markings", [])],
            "deadTransitions": report.get("dead_transitions", []),
            "liveTransitions": report.get("live_transitions", []),
            "impartialTransitions": report.get("impartial_transitions", []),
            "homeMarkings": len(report.get("home_markings", [])),
            "placeBounds": {k: {"min": v[0], "max": v[1]} for k, v in bounds.items()},
            "computationTimeMs": round(stats.get("computation_time", 0) * 1000, 2),
            "targetReachability": target_reach,
            "error": None,
        }
    finally:
        os.unlink(tmp_path)


# -----------------------------------------------------------------------------
#  Response model + endpoint
# -----------------------------------------------------------------------------

class TargetCondition(BaseModel):
    placeName: str
    minTokens: int


class TargetReachabilityResult(BaseModel):
    queried: bool = False
    reachable: bool = False
    matchingMarkings: int = 0
    description: str = ""


class CPNpyRequest(BaseModel):
    xml: str
    targetConditions: Optional[List[TargetCondition]] = None


class CPNpyAnalysisResponse(BaseModel):
    available: bool
    rgNodes: int = 0
    rgArcs: int = 0
    sccNodes: int = 0
    sccArcs: int = 0
    deadMarkings: List[Dict[str, str]] = []
    deadTransitions: List[str] = []
    liveTransitions: List[str] = []
    impartialTransitions: List[str] = []
    homeMarkings: int = 0
    placeBounds: Dict[str, Dict[str, int]] = {}
    computationTimeMs: float = 0
    targetReachability: Optional[TargetReachabilityResult] = None
    error: Optional[str] = None


@router.post("/api/cpn/cpnpy-analyze", response_model=CPNpyAnalysisResponse)
async def cpnpy_analyze(
    request: CPNpyRequest,
    current_user=Depends(get_current_user),
):
    """
    CPN verification via cpnpy.

    Accepts a CPN Tools 4.x XML string produced by the frontend's
    exportToCPNTools(), runs cpnpy's StateSpaceAnalyzer (with empty-multiset
    bug fix), and returns the full analysis: state counts, dead markings,
    transition L4 liveness, place bounds, SCC stats, and home markings.
    """
    if not CPNPY_AVAILABLE:
        return CPNpyAnalysisResponse(
            available=False,
            error="cpnpy is not installed on this server.",
        )

    try:
        conditions = [
            {"placeName": c.placeName, "minTokens": c.minTokens}
            for c in (request.targetConditions or [])
        ]
        result = run_cpnpy_analysis(request.xml, target_conditions=conditions)
        return CPNpyAnalysisResponse(**result)
    except Exception as exc:
        return CPNpyAnalysisResponse(
            available=True,
            error=str(exc),
        )
