"""
CPNpy Analysis Endpoint - Tier-3 state-space verification via cpnpy

Receives a CPN Tools 4.x XML string (generated by the frontend's
exportToCPNTools()), runs cpnpy's StateSpaceAnalyzer (with an
empty-multiset bug workaround), and returns:
  - Reachability graph node / arc counts
  - Dead markings (terminal states) with human-readable token strings
  - Dead / live / impartial transitions
  - Per-place token bounds
  - SCC graph stats and home markings
  - Computation time
"""
import os
import re
import tempfile
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from src.auth.jwthandler import get_current_user

router = APIRouter()

# -----------------------------------------------------------------------------
#  Optional cpnpy import (gracefully absent in environments without it)
# -----------------------------------------------------------------------------
try:
    from cpnpy.util.conversion.cpn_xml_to_json import cpn_xml_to_json as _cpn_xml_to_json
    from cpnpy.cpn import importer as _cpn_importer
    from cpnpy.cpn.cpn_imp import Marking as _CPNMarking
    from cpnpy.analysis.reachability import (
        build_reachability_graph as _build_rg,
        make_hashable as _make_hashable,
    )
    from cpnpy.analysis.scc import build_scc_graph as _build_scc
    from cpnpy.analysis.analyzer import StateSpaceAnalyzer as _StateSpaceAnalyzer
    CPNPY_AVAILABLE = True
except ImportError:
    CPNPY_AVAILABLE = False


# -----------------------------------------------------------------------------
#  SML → Python translation helpers
# -----------------------------------------------------------------------------

def _sml_guard_to_python(raw: str) -> str:
    raw = raw.strip()
    raw = re.sub(r"\btrue\b",  "True",  raw)
    raw = re.sub(r"\bfalse\b", "False", raw)
    raw = re.sub(r"\bmod\b",   "%",     raw)
    raw = raw.replace("<>", "!=")
    raw = re.sub(r"(?<![=!<>])=(?!=)", "==", raw)
    return raw


def _sml_arc_to_python(expr: str) -> str:
    expr = expr.strip()
    m = re.match(r"^\d+`(.+)$", expr, re.DOTALL)
    if m:
        expr = m.group(1).strip()
    expr = re.sub(r"\btrue\b",  "True",  expr)
    expr = re.sub(r"\bfalse\b", "False", expr)
    return expr


_NOT_VAR_NAMES = {"True", "False", "None", "and", "or", "not", "in", "is"}


def _arc_vars(expr: str) -> List[str]:
    result = []
    for name in re.findall(r"[a-zA-Z_]\w*", expr):
        if name not in _NOT_VAR_NAMES and name[0].islower() and name not in result:
            result.append(name)
    return result


def _fix_token(tok: Any) -> Any:
    if tok == "true":  return True
    if tok == "false": return False
    return tok


# -----------------------------------------------------------------------------
#  cpnpy empty-multiset bug workaround
#  remove_tokens() leaves empty Multiset entries in _marking, causing
#  semantically identical markings to hash differently depending on path.
# -----------------------------------------------------------------------------

def _normalized_equiv(m: Any) -> Tuple:
    entries = []
    for place_name, ms in sorted(m._marking.items()):
        if not ms.tokens:
            continue
        tok_list = tuple(
            sorted((_make_hashable(t.value), _make_hashable(t.timestamp))
                   for t in ms.tokens)
        )
        entries.append((place_name, tok_list))
    return (m.global_clock, tuple(entries))


# -----------------------------------------------------------------------------
#  Core analysis pipeline
# -----------------------------------------------------------------------------

def run_cpnpy_analysis(xml_str: str) -> Dict[str, Any]:
    """
    Write XML to a temp file, run the full cpnpy state-space pipeline,
    and return a plain dict of results.
    """
    with tempfile.NamedTemporaryFile(suffix=".cpn", mode="w",
                                     encoding="iso-8859-1", delete=False) as fh:
        fh.write(xml_str)
        tmp_path = fh.name

    try:
        # 1. XML → cpnpy JSON dict
        data = _cpn_xml_to_json(tmp_path)

        # 1b. Normalise unsupported colorset syntax before the cpnpy parser sees it.
        #     CPN Tools allows ranged integer subsets: "colset X = int with lo..hi;"
        #     cpnpy's ColorSetParser only recognises plain "int", so strip the
        #     range clause — cpnpy does not enforce colour-set membership anyway.
        data["colorSets"] = [
            re.sub(r"\bint\s+with\s+-?\d+\.\.-?\d+\b", "int", cs)
            for cs in data.get("colorSets", [])
        ]

        # 2. Re-extract guards: cpn_xml_to_json reads <condition/annot/text>
        #    but CPN Tools 4 / our exporter stores guards in <cond><text>.
        tree = ET.parse(tmp_path)
        root = tree.getroot()
        trans_guard: Dict[str, str] = {}
        for t_elem in root.findall(".//trans"):
            tname_elt = t_elem.find("text")
            tname = tname_elt.text.strip() if (tname_elt is not None and tname_elt.text) else ""
            cond = t_elem.find("cond")
            if cond is not None:
                txt = cond.find("text")
                if txt is not None and txt.text and txt.text.strip():
                    trans_guard[tname] = _sml_guard_to_python(txt.text)
        for t in data["transitions"]:
            if t["name"] in trans_guard:
                t["guard"] = trans_guard[t["name"]]

        # 3. Fix arc expressions and derive missing variable lists
        for t in data["transitions"]:
            t["inArcs"]  = [{"place": a["place"],
                              "expression": _sml_arc_to_python(a["expression"])}
                             for a in t["inArcs"]]
            t["outArcs"] = [{"place": a["place"],
                              "expression": _sml_arc_to_python(a["expression"])}
                             for a in t["outArcs"]]
            if not t["variables"]:
                seen: List[str] = []
                for a in t["inArcs"]:
                    for v in _arc_vars(a["expression"]):
                        if v not in seen:
                            seen.append(v)
                t["variables"] = seen

        # 4. Fix initial-marking boolean tokens (cpnpy returns strings)
        for mk in data["initialMarking"].values():
            mk["tokens"] = [_fix_token(tok) for tok in mk["tokens"]]

        # 5. Build cpnpy model objects
        cpn_obj, marking, context = _cpn_importer.import_cpn_from_json(data)

        # 6. Build corrected reachability graph
        analyzer = _StateSpaceAnalyzer(cpn_obj, marking, context)
        analyzer.RG = _build_rg(cpn_obj, marking, context,
                                 marking_equiv_func=_normalized_equiv)
        analyzer.SG = _build_scc(analyzer.RG)
        analyzer.marking_to_enabled_transitions = {}
        analyzer._precompute_enabled_transitions()

        report = analyzer.summarize()

        # 7. Decode dead markings into human-readable {place: token_string} dicts
        def _decode_dead(node_key: Tuple) -> Dict[str, str]:
            _ts, places = node_key
            out: Dict[str, str] = {}
            for name, toks in places:
                if toks:
                    strs = []
                    for val, _stamp in toks:
                        if val == ():
                            strs.append("1`()")
                        elif isinstance(val, bool):
                            strs.append(f"1`{'true' if val else 'false'}")
                        else:
                            strs.append(f"1`{val}")
                    out[name] = " ++ ".join(strs)
                else:
                    out[name] = "empty"
            return out

        stats = report.get("statistics", {})
        bounds = report.get("place_bounds", {})

        return {
            "available": True,
            "rgNodes": stats.get("RG_nodes", 0),
            "rgArcs": stats.get("RG_arcs", 0),
            "sccNodes": stats.get("SCC_nodes", 0),
            "sccArcs": stats.get("SCC_arcs", 0),
            "deadMarkings": [_decode_dead(n) for n in report.get("dead_markings", [])],
            "deadTransitions": report.get("dead_transitions", []),
            "liveTransitions": report.get("live_transitions", []),
            "impartialTransitions": report.get("impartial_transitions", []),
            "homeMarkings": len(report.get("home_markings", [])),
            "placeBounds": {k: {"min": v[0], "max": v[1]} for k, v in bounds.items()},
            "computationTimeMs": round(stats.get("computation_time", 0) * 1000, 2),
            "error": None,
        }
    finally:
        os.unlink(tmp_path)


# -----------------------------------------------------------------------------
#  Response model + endpoint
# -----------------------------------------------------------------------------

class CPNpyRequest(BaseModel):
    xml: str


class CPNpyAnalysisResponse(BaseModel):
    available: bool
    rgNodes: int = 0
    rgArcs: int = 0
    sccNodes: int = 0
    sccArcs: int = 0
    deadMarkings: List[Dict[str, str]] = []
    deadTransitions: List[str] = []
    liveTransitions: List[str] = []
    impartialTransitions: List[str] = []
    homeMarkings: int = 0
    placeBounds: Dict[str, Dict[str, int]] = {}
    computationTimeMs: float = 0
    error: Optional[str] = None


@router.post("/api/cpn/cpnpy-analyze", response_model=CPNpyAnalysisResponse)
async def cpnpy_analyze(
    request: CPNpyRequest,
    current_user=Depends(get_current_user),
):
    """
    Tier-3 CPN verification via cpnpy.

    Accepts a CPN Tools 4.x XML string produced by the frontend's
    exportToCPNTools(), runs cpnpy's StateSpaceAnalyzer (with empty-multiset
    bug fix), and returns the full analysis: state counts, dead markings,
    transition liveness, place bounds, SCC stats, and home markings.
    """
    if not CPNPY_AVAILABLE:
        return CPNpyAnalysisResponse(
            available=False,
            error="cpnpy is not installed on this server.",
        )

    try:
        result = run_cpnpy_analysis(request.xml)
        return CPNpyAnalysisResponse(**result)
    except Exception as exc:
        return CPNpyAnalysisResponse(
            available=True,
            error=str(exc),
        )
